package com.ikerfah.junction2019.retro

import com.ikerfah.junction2019.models.ProductResponse
import retrofit2.Call
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST
import retrofit2.http.Query


interface ApiService {

    @Headers(
        "Accept:application/json",
        "Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjAzYWE5ZDk5YTRhZmRmM2RhOTg0N2Q1NWFjMzdhYjMwZTAxZDUyMWNmYWQyZmFjNGY1MjJjYzk0MzhmZmVhMDk0NTU0YjVjYmZlNTIzODIwIn0.eyJhdWQiOiIxIiwianRpIjoiMDNhYTlkOTlhNGFmZGYzZGE5ODQ3ZDU1YWMzN2FiMzBlMDFkNTIxY2ZhZDJmYWM0ZjUyMmNjOTQzOGZmZWEwOTQ1NTRiNWNiZmU1MjM4MjAiLCJpYXQiOjE1NzM5NDU1NzQsIm5iZiI6MTU3Mzk0NTU3NCwiZXhwIjoxNjA1NTY3OTc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.duToxTr9sr0husRkvfPokumXYRE4h0GpZzolvnmQNLVlbGfAAvvbPp_WA1nPVj8Uf_fQQZbKfD5J63gGi9LTyq3GLxbwHs_t5EDWROOC7JDmGdQ5Pmpw0n70T9Km8WQM_vKOo8cHzBrZvU5UCQbJnMy0b0eYtOntrjjs9ogVRle9Xov9GDVRb_0GIWl-W8vTw2ubVFRfGJTOeocwIeuHXFCG_Uqr_bYQbQAdN2MPeYghvDkSTCqicLRppgKiUKcA2ofqatZ2za1dOwPQBehm7lkmPW4fcqMdhFthBqFOWMneqxKoLts4xjP8wtILgLR6NhFDBMSmJ0WePG3U9bLcwS0nFfp0Ee8Xrwkb5VoleWHCa4iub6lRGsvHu4SNBQkUgaT8oQvOuJIkV_6QY8ONbCUKMVNHLFrqkaBHOigvefnHGn9BY4p6fLUPQakUnmRh95OYitjpkRfiozmUh5jfx4hQRRLcsLGLda8LyZjz1vT1juPKKMcCf7AeY-gS8v-REMb-MY_gfAKBcntui3DxFoYT8KKw0i91q8BqrwOXoqeBKl4aT4ftqRJtlXpEdPVTpxZWKQ-FzNqwdzMeaK2FaTkcDtT-5AwjfnphCazjqOyEn4e3WXAG1BCi_K8mklTkVgYwk5veI2LzutS9XKADtI_pF-sQTLahq7KiuLsznuY",
        "Content-Type:application/x-www-form-urlencoded"
    )
    @POST("qr/store")
    fun listRepos(

        @Query("qrcode") qrcode: String
    ): Call<ScanRecipeResponse>




    @Headers(
        "Accept:application/json",
        "Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjAzYWE5ZDk5YTRhZmRmM2RhOTg0N2Q1NWFjMzdhYjMwZTAxZDUyMWNmYWQyZmFjNGY1MjJjYzk0MzhmZmVhMDk0NTU0YjVjYmZlNTIzODIwIn0.eyJhdWQiOiIxIiwianRpIjoiMDNhYTlkOTlhNGFmZGYzZGE5ODQ3ZDU1YWMzN2FiMzBlMDFkNTIxY2ZhZDJmYWM0ZjUyMmNjOTQzOGZmZWEwOTQ1NTRiNWNiZmU1MjM4MjAiLCJpYXQiOjE1NzM5NDU1NzQsIm5iZiI6MTU3Mzk0NTU3NCwiZXhwIjoxNjA1NTY3OTc0LCJzdWIiOiIyIiwic2NvcGVzIjpbXX0.duToxTr9sr0husRkvfPokumXYRE4h0GpZzolvnmQNLVlbGfAAvvbPp_WA1nPVj8Uf_fQQZbKfD5J63gGi9LTyq3GLxbwHs_t5EDWROOC7JDmGdQ5Pmpw0n70T9Km8WQM_vKOo8cHzBrZvU5UCQbJnMy0b0eYtOntrjjs9ogVRle9Xov9GDVRb_0GIWl-W8vTw2ubVFRfGJTOeocwIeuHXFCG_Uqr_bYQbQAdN2MPeYghvDkSTCqicLRppgKiUKcA2ofqatZ2za1dOwPQBehm7lkmPW4fcqMdhFthBqFOWMneqxKoLts4xjP8wtILgLR6NhFDBMSmJ0WePG3U9bLcwS0nFfp0Ee8Xrwkb5VoleWHCa4iub6lRGsvHu4SNBQkUgaT8oQvOuJIkV_6QY8ONbCUKMVNHLFrqkaBHOigvefnHGn9BY4p6fLUPQakUnmRh95OYitjpkRfiozmUh5jfx4hQRRLcsLGLda8LyZjz1vT1juPKKMcCf7AeY-gS8v-REMb-MY_gfAKBcntui3DxFoYT8KKw0i91q8BqrwOXoqeBKl4aT4ftqRJtlXpEdPVTpxZWKQ-FzNqwdzMeaK2FaTkcDtT-5AwjfnphCazjqOyEn4e3WXAG1BCi_K8mklTkVgYwk5veI2LzutS9XKADtI_pF-sQTLahq7KiuLsznuY"
    )
    @GET("products/missed")
    fun missedProducts(): Call<ProductResponse>
}